### ISSUE TITLE
Setup OAuth(Thapar.edu)

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/buying_selling_devops#16]

**Comment by jsparmani** [comment]
- [ ] Find what data we already get from Thapar OAuth
- [ ] Restrict OAuth Fields from changing
- [ ] Add other required fields for profile completion

**Comment by jsparmani** [comment]
For this case, the client side would actually be responsible with `react-google-login` to get details and then establish `JWT Auth` between client and the backend for further requests. I am not sure how to restrict this to _thapar.edu_ , probably it would require configuring both backend and frontend. Any idea on setting up _thapar.edu_ - @kush-daga @parthsujalshah

**Comment by jsparmani** [comment]
One way what I found was to let users login with any account, analyze the response that comes back on success and then display a message saying not a _thapar.edu_ account. But that would be a bit misleading. I feel restricting it inherently would be a better user experience.

**Comment by jsparmani** [comment]
Okay, I found a way to ensure that only `thapar.edu` accounts are displayed in the google oauth popup, but this is only a check, we would have to analyze the response for security reasons.

**Comment by kush-daga** [comment]
I'll get to it asap

**Comment by jsparmani** [comment]
Okay, @aniketbiswas21 @kush-daga we are done with the backend setup for this. Any finalised design so that we can start with the UI and integrate it with the backend?

**Comment by jsparmani** [comment]
@aniketbiswas21 you can start integrating `react-google-login` from frontend. 
Here is the [link](https://www.npmjs.com/package/react-google-login).
Also, setup `react` to use environment variables so that I can add the _Google OAuth Cliend ID_ there

**Comment by jsparmani** [comment]
Done
