### ISSUE TITLE
Container Orchestration with Docker Compose for Dev

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/buying_selling_devops#19]

**Comment by jsparmani** [comment]
- [ ] Setup Dockerfile and docker-compose for frontend first
- [ ] Setup docker-compose configs and dockerfile configs for backend and db

@parthsujalshah You can work on part 1 of the checklist during phase 1

**Comment by parthsujalshah** [comment]
okay

**Comment by jsparmani** [comment]
> * [ ]  Setup Dockerfile and docker-compose for frontend first
> * [x]  Setup docker-compose configs and dockerfile configs for backend and db
> * [ ]  Seperate dockerfile for production and development environement
> 
> @parthsujalshah You can work on part 1 of the checklist during phase 1

@parthsujalshah  Can you start working on the 1st part of the checklist?

**Comment by parthsujalshah** [comment]
okay!

**Comment by jsparmani** [comment]
Done
