### ISSUE TITLE
Configure all contributors bot

### ISSUE THREAD

**Issue by shubhank-saxena** [developer-student-club-thapar/buying_selling_devops#34]
Just a fun way to acknowledge our active contributors!
https://probot.github.io/apps/all-contributors/

**Comment by jsparmani** [comment]
@parthsujalshah any progress?

**Comment by parthsujalshah** [comment]
Working...

**Comment by parthsujalshah** [comment]
@shubhank-saxena  @jsparmani  shall I grant the access of the bot to all our repositories or just this one?

**Comment by parthsujalshah** [comment]
@shubhank-saxena 
I am getting a message: "You do not have permission to modify this app on developer-student-club-thapar. Please contact an Organization Owner."

**Comment by shubhank-saxena** [comment]
I think I have done this! Will allow the bots here! 
Thank you!
