### ISSUE TITLE
Configure Django Admin Documentation Generator

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/buying_selling_devops#53]
Check this [link](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/admindocs/) for reference.
I am also open to new options that we could use instead of this @Saurav-Shrivastav @kush-daga

**Comment by jsparmani** [comment]
One more option I found is using **Django Rest Swagger**

**Comment by kush-daga** [comment]
Swagger is an amazing way
